[package]
name = "gurps-point-calculator"
version = "0.2.0"
authors = ["Celti Burroughs <celti@celti.name>"]
edition = "2018"

[dependencies]
anyhow = "1.0.28"
once_cell = "1.3.1"
rayon = "1.3.0"
regex = "1.3.6"
separator = "0.4.1"
